apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-service
  name: external-service
  namespace: nginx
spec:
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.148.0.101
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: nginx-ingress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.148.0.101
